#!/usr/bin/env python

import os

Import("env")
Import("env_modules")

env_ffmpeg = env_modules.Clone()

env_ffmpeg.Append(CPPPATH=["include"])
env.Append(LIBPATH=[os.environ.get("FFMPEG_LIBPATH", "")])

LIBS = env.get("LIBS", "")
env.Append(LIBS=["avdevice", "avformat", "avcodec", "avutil", "avfilter", "swresample", "swscale"])

module_obj = []
env_ffmpeg.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

env_ffmpeg.disable_warnings()
